### ISSUE TITLE
Add LAG information to f5os_device_info module

### ISSUE THREAD

**Issue by Omripresent** [F5Networks/f5-ansible-f5os#3]
### Is your feature request related to a problem? Please describe.
When using the f5os_lag module you have to specify all of the vlans you want assigned, adding a single to existing is not possible and using f5os_device_info doesn't list the existing LAGs vlan information.

### Describe the solution you'd like
Under the interfaces subset add the currently configured vlans and possibly other config values like LAG members, type, speed, and so on.

### Describe alternatives you've considered
Not using the F5OS module and making direct API calls

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1307

**Comment by wojtek0806** [comment]
will be added in 1.4.0 closing
