### ISSUE TITLE
F5OS remote system authentication

### ISSUE THREAD

**Issue by MVogel91** [F5Networks/f5-ansible-f5os#8]
### Is your feature request related to a problem? Please describe.
F5OS Ansible modules currently don't support configuration of remote authentication as in configuring the various authentication providers.

### Describe the solution you'd like
If configuration would be split per protocol, RADIUS would be my highest priority, however the future state should allow to configure any remote authentication protocol.
The modules should also allow to define remote role assignment.

### Describe alternatives you've considered
Drop out of Ansible and configure these through API, CLI or GUI.

### Additional context
My customer operates a large landscape of iSeries to be swapped by rSeries. A unified onboarding through Ansible would heavily reduce the efforts

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1598.

**Comment by urohit011** [comment]
This is done, so closing the issue.
